### ISSUE TITLE
I cant record Rinex file

### ISSUE THREAD

**Issue by Neroliuxx** [DoopDip/GnssRecord#1]
When i start record.it always get zero data.When i use Geo++ ,it's OK,and it can get all the info that i need .Can you Tell me how to fix it? THX!!!!

**Comment by Neroliuxx** [comment]
Satellite total : 0，but In the RecordActivity ,it has several satellite.

**Comment by DoopDip** [comment]
@Neroliuxx  The problem has been resolved. You can pull code for new update.
Thank you for your interested :D
